name: Deploy to Vercel via Deploy Hook

on:
  push:
    branches:
      - master  # Or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Vercel Deploy Hook
      env:
        DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
      run: |
        curl -X POST $DEPLOY_HOOK_URL
