name: Sync Repo to Vercel Deployment Repo

on:
  push:
    branches:
      - master  # Trigger on changes to the 'master' branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
    - name: Add Vercel Deployment Repo as a remote
      run: |
        git remote add vercel https://$TOKEN@github.com/blueparrottech/blueparrottech.git
      env:
        TOKEN: ${{ secrets.VERCELREPO_TOKEN }}  # PAT stored as a secret

    - name: Push changes to Vercel Deployment Repo
      run: |
        # Check for changes and push if there are any
        if [[ -n "$(git status --porcelain)" ]]; then
          git add .
          git commit -m "Mirror changes to Vercel deployment repo"
          git push vercel master --force
        else
          echo "No changes to commit and push"
        fi
      env:
        TOKEN: ${{ secrets.VERCELREPO_TOKEN }}
