name: Mirror to Repo 2 and Deploy to Vercel

on:
  push:
    branches:
      - master  # Or your primary branch in repo 1

jobs:
  mirror_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Add Repo 2 as a remote
      env:
        TOKEN: ${{ secrets.REPO2_TOKEN }}
      run: |
        git remote add repo2 https://$TOKEN@github.com/blueparrottech/blueparrottech.git

    - name: Push changes to Repo 2
      run: |
        git push repo2 master --force

    - name: Trigger Vercel Deploy Hook
      env:
        DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
      run: |
        curl -X POST $DEPLOY_HOOK_URL
